<div class="col-5 overflow-auto h-100">
            <ul class=" navbar-nav">
                <h6>Aali Imran</h6>
                <h5>Ayat No.</h5>
            <li class=" nav-item"><a class=" nav-link" href="#1-5">1-5</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#6-10">6-10</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#26-28">26-28</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#29-32">29-32</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#81-83">81-83</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#178-180">178-80</a></li>
            <!--<li class=" nav-item"><a class=" nav-link" href="#2">2</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#3">3</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#4">4</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#5">5</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#6">6</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#7">7</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#8">8</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#9">9</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#10">10</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#11">11</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#12">12</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#13">13</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#14">14</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#15">15</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#16">16</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#17">17</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#18">18</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#19">19</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#20">20</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#21">21</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#22">22</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#23">23</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#24">24</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#25">25</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#26">26</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#27">27</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#28">28</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#29">29</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#30">30</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#31">31</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#32">32</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#33">33</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#34">34</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#35">35</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#36">36</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#37">37</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#38">38</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#39">39</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#40">40</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#41">41</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#42">42</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#43">43</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#44">44</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#45">45</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#46">46</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#47">47</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#48">48</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#49">49</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#50">50</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#51">51</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#52">52</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#53">53</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#54">54</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#55">55</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#56">56</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#57">57</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#58">58</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#59">59</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#60">60</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#61">61</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#62">62</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#63">63</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#64">64</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#65">65</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#66">66</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#67">67</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#68">68</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#69">69</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#70">70</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#71">71</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#72">72</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#73">73</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#74">74</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#75">75</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#76">76</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#77">77</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#78">78</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#79">79</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#80">80</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#81">81</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#82">82</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#83">83</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#84">84</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#85">85</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#86">86</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#87">87</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#88">88</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#89">89</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#90">90</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#91">91</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#92">92</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#93">93</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#94">94</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#95">95</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#96">96</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#97">97</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#98">98</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#99">99</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#100">100</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#101">101</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#102">102</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#103">103</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#104">104</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#105">105</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#106">106</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#107">107</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#108">108</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#109">109</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#110">110</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#111">111</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#112">112</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#113">113</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#114">114</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#115">115</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#116">116</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#117">117</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#118">118</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#119">119</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#120">120</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#121">121</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#122">122</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#123">123</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#124">124</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#125">125</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#126">126</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#127">127</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#128">128</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#129">129</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#130">130</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#131">131</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#132">132</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#132">132</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#133">133</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#133">133</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#134">134</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#135">135</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#136">136</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#137">137</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#138">138</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#139">139</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#140">140</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#141">141</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#142">142</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#143">143</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#144">144</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#145">145</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#146">146</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#147">147</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#148">148</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#149">149</a></li>
            <li class=" nav-item"><a class=" nav-link" href="#150">150</a></li>-->
            <!--<li class="nav-item"><a class="w3-codespan" href="#align-items">align-items</a></li>-->
            </ul>
            </div>